# Generated by Django 5.1.3 on 2024-11-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book/', verbose_name='Загрузите картинку')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название книги')),
                ('description', models.TextField(verbose_name='Укажите описание к книге')),
                ('price', models.FloatField(verbose_name='Укажите цену')),
                ('start_book', models.DateField(verbose_name='Укажите дату выхода')),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Романтика', 'Романтика'), ('Научный', 'Научный')], default='Фантастика', max_length=100, verbose_name='Укажите жанр')),
                ('email', models.EmailField(max_length=254, verbose_name='Укажите почту автора')),
                ('author', models.CharField(max_length=30, verbose_name='Укажите имя автора')),
                ('trailer', models.URLField(verbose_name='Укажите ссылку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
    ]
