# Generated by Django 5.1.3 on 2024-11-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='trailer',
        ),
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.URLField(null=True, verbose_name='Укажите ссылку'),
        ),
    ]
